# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository:
  tag:
  name:
  credSecret:
  pullPolicy: IfNotPresent
application:
  app_env: dev
  debug: false
  migrateCommand: bin/console doctrine:migrations:migrate --no-interaction
  cacheInvalidationCommand: bin/console doctrine:cache:clear-result
  track: stable
sentry:
  branch:
  commit:
service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: test.lstv.io
  commonName:
  externalPort: 80
  internalPort: 80
ingress:
  tls:
    enabled: true
    secretName: ""
  redirectToWww: false
  issuer:
livenessProbe:
  path: "/healthz"
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  scheme: "HTTP"
readinessProbe:
  path: "/healthz"
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  scheme: "HTTP"
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 400m
    memory: 256Mi
## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
horizontalPodAutoscaler:
  maxReplicaCount: 5
  metrics:
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50